/* Generated By:JavaCC: Do not edit this line. BasicConstants.java */
package edu.itsco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 5;
  /** RegularExpression Id. */
  int FIN = 6;
  /** RegularExpression Id. */
  int IMPRIMIR = 7;
  /** RegularExpression Id. */
  int LEER = 8;
  /** RegularExpression Id. */
  int SI = 9;
  /** RegularExpression Id. */
  int ENTONCES = 10;
  /** RegularExpression Id. */
  int SINO = 11;
  /** RegularExpression Id. */
  int DESDE = 12;
  /** RegularExpression Id. */
  int HASTA = 13;
  /** RegularExpression Id. */
  int SIGUIENTE = 14;
  /** RegularExpression Id. */
  int HACER = 15;
  /** RegularExpression Id. */
  int MIENTRAS = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int ENTERO = 18;
  /** RegularExpression Id. */
  int DECIMAL = 19;
  /** RegularExpression Id. */
  int CADENA = 20;
  /** RegularExpression Id. */
  int SELECCIONA = 21;
  /** RegularExpression Id. */
  int CASO = 22;
  /** RegularExpression Id. */
  int ROMPE = 23;
  /** RegularExpression Id. */
  int SUMA = 24;
  /** RegularExpression Id. */
  int RESTA = 25;
  /** RegularExpression Id. */
  int MULTI = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int RESIDUO = 28;
  /** RegularExpression Id. */
  int IGUAL = 29;
  /** RegularExpression Id. */
  int MAYOR = 30;
  /** RegularExpression Id. */
  int MENOR = 31;
  /** RegularExpression Id. */
  int AND = 32;
  /** RegularExpression Id. */
  int OR = 33;
  /** RegularExpression Id. */
  int NOT = 34;
  /** RegularExpression Id. */
  int DP = 35;
  /** RegularExpression Id. */
  int AP = 36;
  /** RegularExpression Id. */
  int CP = 37;
  /** RegularExpression Id. */
  int AC = 38;
  /** RegularExpression Id. */
  int CC = 39;
  /** RegularExpression Id. */
  int digito = 40;
  /** RegularExpression Id. */
  int letra = 41;
  /** RegularExpression Id. */
  int ID = 42;
  /** RegularExpression Id. */
  int VALOR_ENTERO = 43;
  /** RegularExpression Id. */
  int VALOR_DECIMAL = 44;
  /** RegularExpression Id. */
  int VALOR_CADENA = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"inicio\"",
    "\"fin\"",
    "\"imprimir\"",
    "\"leer\"",
    "\"si\"",
    "\"entonces\"",
    "\"sino\"",
    "\"desde\"",
    "\"hasta\"",
    "\"siguiente\"",
    "\"hacer\"",
    "\"mientras\"",
    "\"var\"",
    "\"entero\"",
    "\"decimal\"",
    "\"cadena\"",
    "\"selecciona\"",
    "\"caso\"",
    "\"rompe\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<digito>",
    "<letra>",
    "<ID>",
    "<VALOR_ENTERO>",
    "<VALOR_DECIMAL>",
    "<VALOR_CADENA>",
  };

}
